Repository MaelSemler/mini-cap, pull requests merged in 2020-03, with the labels that each got.

#109 Dev 9 autocomplete on search fields
  app/build.gradle
  app/src/main/java/com/soen390/conumap/MainActivity.kt
  app/src/main/java/com/soen390/conumap/ui/search_bar/SearchBarFragment.kt
  app/src/main/java/com/soen390/conumap/ui/search_results/SearchResultsFragment.kt
  app/src/main/res/layout/search_bar_fragment.xml
  app/src/main/res/layout/search_results_fragment.xml
Labels: Priority 1, enhancement

#123 Ft4 4 shortest path
  app/src/main/java/com/soen390/conumap/IndoorNavigation/Node.kt
  app/src/main/java/com/soen390/conumap/IndoorNavigation/NodeComparator.kt
  app/src/main/java/com/soen390/conumap/IndoorNavigation/PathFindingSampleTest.kt
  app/src/main/java/com/soen390/conumap/IndoorNavigation/Pathfinding.kt
Labels: back-end

#138 Fixed issue where buildings would disappear when getting directions
  app/src/main/java/com/soen390/conumap/map/Map.kt
Labels: Bug

#139 DEF13 + DEF14
  app/src/main/java/com/soen390/conumap/Directions/DirectionService.kt
  app/src/main/java/com/soen390/conumap/path/path.kt
  app/src/main/java/com/soen390/conumap/ui/directions/AlternateFragment.kt
  app/src/main/java/com/soen390/conumap/ui/directions/AlternateViewModel.kt
  app/src/main/java/com/soen390/conumap/ui/directions/DirectionsFragment.kt
  app/src/main/java/com/soen390/conumap/ui/directions/DirectionsViewModel.kt
  app/src/main/java/com/soen390/conumap/ui/search_results/SearchResultsFragment.kt
  app/src/main/res/layout/alternate_fragment.xml
  app/src/main/res/layout/directions_fragment.xml
Labels: Bug

#153 Dev 23.2 modify side menu
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/soen390/conumap/mainActivity/MainActivity.kt
  app/src/main/java/com/soen390/conumap/ui/home/HomeViewModel.kt
  app/src/main/java/com/soen390/conumap/ui/slideshow/SlideshowViewModel.kt
  app/src/main/res/drawable/side_nav_bar.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
